### ISSUE TITLE
Failed parsing affix_loot_entries file apotheotic_additions:XXX

### ISSUE THREAD

**Issue by Bluebottle39** [Bryce792/ApotheoticAdditions#1]
Hey there,
I'm getting a lot of errors of the type in the title and was wondering if I should be concerned?

Here is the log:
[latest.log](https://github.com/Bryce792/ApotheoticAdditions/files/13428985/latest.log)

Kind regards

**Comment by magix39** [comment]
I wanted to also echo this concern as I noticed a lot of these errors as well.
