### ISSUE TITLE
Affixes 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [Bryce792/ApotheoticAdditions#20]
apotheotic_additions1.5.jar

> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:ringRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:an_focusRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:necklaceRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:charmRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:beltRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:spellstoneRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:scrollRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:braceletRequired: 4; Provided: 3
> [02Mar2024 19:28:25.568] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:talismanRequired: 4; Provided: 3
> [02Mar2024 19:28:25.571] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category bootsRequired: 3; Provided: 2
> [02Mar2024 19:28:25.571] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:ringRequired: 3; Provided: 2
> [02Mar2024 19:28:25.571] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:necklaceRequired: 3; Provided: 2
> [02Mar2024 19:28:25.571] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:charmRequired: 3; Provided: 2
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:ringRequired: 4; Provided: 3
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:an_focusRequired: 4; Provided: 3
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:necklaceRequired: 4; Provided: 3
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:charmRequired: 4; Provided: 3
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:beltRequired: 4; Provided: 3
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:spellstoneRequired: 4; Provided: 3
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:scrollRequired: 4; Provided: 3
> [02Mar2024 19:28:25.572] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:braceletRequired: 4; Provided: 3
> [02Mar2024 19:28:25.573] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:talismanRequired: 4; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category pickaxeRequired: 5; Provided: 4
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category shovelRequired: 5; Provided: 4
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category swordRequired: 5; Provided: 4
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:ringRequired: 5; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:an_focusRequired: 5; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:necklaceRequired: 5; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:charmRequired: 5; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:beltRequired: 5; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:spellstoneRequired: 5; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:scrollRequired: 5; Provided: 3
> [02Mar2024 19:28:25.574] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:braceletRequired: 5; Provided: 3
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:talismanRequired: 5; Provided: 3
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category pickaxeRequired: 5; Provided: 3
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category shovelRequired: 5; Provided: 3
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category helmetRequired: 5; Provided: 4
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category chestplateRequired: 5; Provided: 4
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category leggingsRequired: 5; Provided: 4
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category bootsRequired: 5; Provided: 4
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category shieldRequired: 5; Provided: 3
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:ringRequired: 5; Provided: 3
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:an_focusRequired: 5; Provided: 3
> [02Mar2024 19:28:25.575] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:necklaceRequired: 5; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:charmRequired: 5; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:beltRequired: 5; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:spellstoneRequired: 5; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:scrollRequired: 5; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:braceletRequired: 5; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:talismanRequired: 5; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category helmetRequired: 4; Provided: 3
> [02Mar2024 19:28:25.576] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 2
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:ringRequired: 4; Provided: 2
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:an_focusRequired: 4; Provided: 3
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:necklaceRequired: 4; Provided: 2
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:charmRequired: 4; Provided: 2
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:beltRequired: 4; Provided: 3
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:spellstoneRequired: 4; Provided: 3
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:scrollRequired: 4; Provided: 3
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:braceletRequired: 4; Provided: 3
> [02Mar2024 19:28:25.577] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:talismanRequired: 4; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shieldRequired: 5; Provided: 4
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:ringRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:an_focusRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:necklaceRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:charmRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:beltRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:spellstoneRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:scrollRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:braceletRequired: 5; Provided: 3
> [02Mar2024 19:28:25.578] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:talismanRequired: 5; Provided: 3
>

**Comment by Bryce792** [comment]
Adding documentation tag to this to work on for future updates.

**Comment by Krimatoria** [comment]
> Добавлен тег документации к этому для работы над будущими обновлениями.

Do you mean it's not an error, but a warning?

**Comment by Bryce792** [comment]
Kinda, its a a baseline log output it looks like from Apotheosis when there isn't enough affixes to satisfy a specific category. So for example, if 5 effects are present on an esoteric item, but only 2 are loaded in, it will create this error as 2/5 are loaded, hence is why there are still some for ancient.

It wont crash to my knowledge, as it has minimum 1 effect, but if say an esoteric was to be loaded when no effects are able to be put on that slot, it would crash.

**Comment by Krimatoria** [comment]
> Это своего рода базовый вывод журнала, который выглядит как из Apotheosis, когда не хватает аффиксов для соответствия определенной категории. Так, например, если на эзотерическом предмете присутствует 5 эффектов, но загружено только 2, возникнет эта ошибка, поскольку загружено 2/5, поэтому для древних еще есть некоторые эффекты.
> 
> Насколько мне известно, он не вылетит, так как имеет минимум 1 эффект, но если, скажем, нужно было загрузить эзотерический предмет, когда в этот слот нельзя поместить никакие эффекты, он вылетит.

I will send the updated part of the log in a few minutes, maybe there is something interesting there.
