### ISSUE TITLE
Translate RU 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [Bryce792/ApotheoticAdditions#22]
apotheotic_additions1.5.jar
Apotheosis-1.20.1-7.3.1.jar

Or is it a problem of apotheosis?
![2024-03-04_19 52 45](https://github.com/Bryce792/ApotheoticAdditions/assets/106809386/c7c3c6c2-f913-4598-957a-46368d419c44)

**Comment by Bryce792** [comment]
I believe its a translation issue with AttributesLib, the user that submitted the Russian translation sent it a while back, and the only two attributes it has in it are from passive skill tree.
