### ISSUE TITLE
apotheotic_additions1.5.jar trojan:script/wacatac.B!ml

### ISSUE THREAD

**Issue by GrizzBear01** [Bryce792/ApotheoticAdditions#23]
file is flagged as trojan and removed as soon as its downloaded

downloaded from curseforge

![Screenshot 2024-03-05 190909](https://github.com/Bryce792/ApotheoticAdditions/assets/111651001/7f72b581-3cfb-4873-88a4-ddec9eb9a987)

**Comment by Gbergz** [comment]
can confirm this, detected by bitdefender while scanning it.

**Comment by Bryce792** [comment]
Going to attempt to replicate this, was this via curseforge launcher, or manual download?

**Comment by Gbergz** [comment]
CurseForge Launcher is where I grabbed and scanned the jar

**Comment by Bryce792** [comment]
So after doing some research, and un-compiling the mod, it looks like its mainly the mcCreator code that is flagging it as a false positive. After removing the JAR file and placing it in a seperate folder outside of the jar and scanning that, it came up as fine, but for some reason scanning the jar flags it as a trojan.
![Untitled](https://github.com/Bryce792/ApotheoticAdditions/assets/148484014/ed0932e4-8196-43aa-b16f-db2884fa6d25)

I'm going to look more into this, and most likely attempt to rebuild the mod off of mcCreator if that is the case.

**Comment by Gbergz** [comment]
Gotcha, so it's a false positive. A relief for users reporting this then.

**Comment by Bryce792** [comment]
Looking at the VirusTotal link provided, nearly every single one of the details is from the mcCreator code. I ran a scan of the actual mcCreator workspace aswell, which appears clean too.
![details](https://github.com/Bryce792/ApotheoticAdditions/assets/148484014/7c249b1f-d203-4014-bb8a-33b75d2b452f)
![workspace](https://github.com/Bryce792/ApotheoticAdditions/assets/148484014/217ee16c-5fb0-438f-b988-ffcc47171e88)

**Comment by Bryce792** [comment]
Discovered files creating the false positive, they were unadded structure files, they have since been removed from the latest version of the mod, and versions 1.4 - 1.4.5.1 are now archived due this issue being present in all of them.

**Comment by Gbergz** [comment]
You Archived v1.4 - v1.4.5.1, but v1.5 is also having that issue, as initially reported.

**Comment by Bryce792** [comment]
Missed that part tbh, just archived 1.5 aswell. Thank you for the heads up.
